pipeline:
  name: wifr-sensitivity
description: "Create wifr simulation from input random seeds"
#standby: true
transform:
  image: k8scc01covidacr.azurecr.io/kenchu-wifr-analysis:v8
  image_pull_secrets:
    - k8scc01covidacr-registry-connection
  cmd:
    - "/main.sh"
    - "--params"
    - "/pfs/params/"
    - "--data"
    - "/pfs/data/"
    - "--output"
    - "/pfs/out"
resource_requests:
  memory: "5G"
  cpu: 2
parallelism_spec:
  constant: 2   # use N computers
input:
  cross:
    - pfs:
        name: params
        repo: wifr-params
        glob: "/*/*"
    - pfs:
        name: data
        repo: wifr-data
        glob: "/"
        branch: 2020-04-24_01
