pipeline:
  name: wifr-sensitivity
description: "Create wifr simulation from input random seeds"
standby: true
transform:
  image: k8scc01covidacr.azurecr.io/kenchu-wifr-git:v1
  image_pull_secrets:
    - k8scc01covidacr-registry-connection
  cmd:
    - "/main.sh"
    - "--src"
    - "/pfs/git/src/"
    - "--params"
    - "/pfs/params/"
    - "--data"
    - "/pfs/data/"
    - "--output"
    - "/pfs/out"
resource_requests:
  memory: "6G"
  cpu: 3
parallelism_spec:
  constant: 100  # use N computers
output_branch: 2020-04-24_01
input:
  cross:
    - pfs:
        name: params
        repo: wifr-params
        glob: "/*/*"
    - pfs:
        name: data
        repo: wifr-data
        glob: "/"
        branch: 2020-04-24_01
    - git:
        name: git
        URL: "https://github.com/kennethchu-statcan/covid19-pachyderm.git"
        branch: master
